// <auto-generated />
using System;
using BlazorWasmDotNet8AspNetCoreHosted.Server.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorWasmDotNet8AspNetCoreHosted.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251205100906_ModuleTopicInterAssemblyFlag")]
    partial class ModuleTopicInterAssemblyFlag
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.BuildingTravel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FromBuildingId")
                        .HasColumnType("int");

                    b.Property<int>("Minutes")
                        .HasColumnType("int");

                    b.Property<int>("ToBuildingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ToBuildingId");

                    b.HasIndex("FromBuildingId", "ToBuildingId")
                        .IsUnique();

                    b.ToTable("BuildingTravels");
                });

            modelBuilder.Entity("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.CalendarException", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("IsWorkingDay")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("CalendarExceptions");
                });

            modelBuilder.Entity("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DurationWeeks")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StudentsCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.LessonTypeRef", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("BlocksRoom")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("BlocksTeacher")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("CountInLoad")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CountInPlan")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CssKey")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("PreferredFirstInWeek")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RequiresRoom")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RequiresTeacher")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("LessonTypes", (string)null);
                });

            modelBuilder.Entity("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.LunchConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("End")
                        .HasColumnType("time(6)");

                    b.Property<TimeOnly>("Start")
                        .HasColumnType("time(6)");

                    b.HasKey("Id");

                    b.ToTable("LunchConfigs");
                });

            modelBuilder.Entity("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<decimal>("Credits")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(6,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.ModuleBuilding", b =>
                {
                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.HasKey("ModuleId", "BuildingId");

                    b.HasIndex("BuildingId");

                    b.ToTable("ModuleBuildings");
                });

            modelBuilder.Entity("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.ModuleCourse", b =>
                {
                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.HasKey("ModuleId", "CourseId");

                    b.HasIndex("CourseId", "ModuleId")
                        .IsUnique();

                    b.ToTable("ModuleCourses");
                });

            modelBuilder.Entity("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.ModuleFiller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.HasIndex("CourseId", "ModuleId")
                        .IsUnique();

                    b.ToTable("ModuleFillers");
                });

            modelBuilder.Entity("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.ModulePlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<int>("ScheduledHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TargetHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.HasIndex("CourseId", "ModuleId")
                        .IsUnique();

                    b.ToTable("ModulePlans");
                });

            modelBuilder.Entity("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.ModuleRoom", b =>
                {
                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("ModuleId", "RoomId");

                    b.HasIndex("RoomId");

                    b.ToTable("ModuleRooms");
                });

            modelBuilder.Entity("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.ModuleSequenceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.HasIndex("CourseId", "ModuleId")
                        .IsUnique();

                    b.HasIndex("CourseId", "Order")
                        .IsUnique();

                    b.ToTable("ModuleSequenceItems");
                });

            modelBuilder.Entity("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.ModuleSupervisor", b =>
                {
                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.HasKey("TeacherId", "ModuleId");

                    b.HasIndex("ModuleId", "TeacherId")
                        .IsUnique();

                    b.ToTable("ModuleSupervisors");
                });

            modelBuilder.Entity("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.ModuleTopic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuditoriumHours")
                        .HasColumnType("int");

                    b.Property<bool>("IsInterAssembly")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<int>("LessonTypeId")
                        .HasColumnType("int");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("SelfStudyHours")
                        .HasColumnType("int");

                    b.Property<string>("TopicCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("TotalHours")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LessonTypeId");

                    b.HasIndex("ModuleId", "Order")
                        .IsUnique();

                    b.HasIndex("ModuleId", "TopicCode")
                        .IsUnique();

                    b.ToTable("ModuleTopics");
                });

            modelBuilder.Entity("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.ScheduleItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time(6)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSelfStudy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<int>("LessonTypeId")
                        .HasColumnType("int");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<int?>("ModuleTopicId")
                        .HasColumnType("int");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time(6)");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("LessonTypeId");

                    b.HasIndex("ModuleId");

                    b.HasIndex("ModuleTopicId");

                    b.HasIndex("RoomId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("Date", "GroupId");

                    b.HasIndex("Date", "RoomId");

                    b.HasIndex("Date", "TeacherId");

                    b.ToTable("ScheduleItems");
                });

            modelBuilder.Entity("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcademicTitle")
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ScientificDegree")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.TeacherCourseLoad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ScheduledHours")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherCourseLoads");
                });

            modelBuilder.Entity("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.TeacherDraftItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchKey")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time(6)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSelfStudy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<int>("LessonTypeId")
                        .HasColumnType("int");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<int?>("ModuleTopicId")
                        .HasColumnType("int");

                    b.Property<int?>("PublishedItemId")
                        .HasColumnType("int");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ValidationWarnings")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("LessonTypeId");

                    b.HasIndex("ModuleId");

                    b.HasIndex("ModuleTopicId");

                    b.HasIndex("RoomId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("Date", "GroupId");

                    b.HasIndex("Date", "RoomId");

                    b.HasIndex("Date", "TeacherId");

                    b.ToTable("TeacherDraftItems");
                });

            modelBuilder.Entity("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.TeacherModule", b =>
                {
                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.HasKey("TeacherId", "ModuleId");

                    b.HasIndex("ModuleId");

                    b.ToTable("TeacherModules");
                });

            modelBuilder.Entity("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.TeacherWorkingHour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("End")
                        .HasColumnType("time(6)");

                    b.Property<TimeOnly>("Start")
                        .HasColumnType("time(6)");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherWorkingHours");
                });

            modelBuilder.Entity("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.TimeSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("End")
                        .HasColumnType("time(6)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<TimeOnly>("Start")
                        .HasColumnType("time(6)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId", "SortOrder")
                        .IsUnique();

                    b.ToTable("TimeSlots");
                });

            modelBuilder.Entity("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.BuildingTravel", b =>
                {
                    b.HasOne("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.Building", "From")
                        .WithMany()
                        .HasForeignKey("FromBuildingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.Building", "To")
                        .WithMany()
                        .HasForeignKey("ToBuildingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("From");

                    b.Navigation("To");
                });

            modelBuilder.Entity("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.Group", b =>
                {
                    b.HasOne("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.Course", "Course")
                        .WithMany("Groups")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.Module", b =>
                {
                    b.HasOne("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.Course", "Course")
                        .WithMany("Modules")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.ModuleBuilding", b =>
                {
                    b.HasOne("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.Building", "Building")
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.Module", "Module")
                        .WithMany("AllowedBuildings")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.ModuleCourse", b =>
                {
                    b.HasOne("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.Course", "Course")
                        .WithMany("ModuleCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.Module", "Module")
                        .WithMany("ModuleCourses")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.ModuleFiller", b =>
                {
                    b.HasOne("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.Module", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.ModulePlan", b =>
                {
                    b.HasOne("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.Module", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.ModuleRoom", b =>
                {
                    b.HasOne("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.Module", "Module")
                        .WithMany("AllowedRooms")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.Room", "Room")
                        .WithMany("ModuleRooms")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.ModuleSequenceItem", b =>
                {
                    b.HasOne("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.Module", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.ModuleSupervisor", b =>
                {
                    b.HasOne("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.Module", "Module")
                        .WithMany("ModuleSupervisors")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.Teacher", "Teacher")
                        .WithMany("ModuleSupervisions")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.ModuleTopic", b =>
                {
                    b.HasOne("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.LessonTypeRef", "LessonType")
                        .WithMany()
                        .HasForeignKey("LessonTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.Module", "Module")
                        .WithMany("Topics")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LessonType");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.Room", b =>
                {
                    b.HasOne("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.Building", "Building")
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.ScheduleItem", b =>
                {
                    b.HasOne("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.LessonTypeRef", "LessonType")
                        .WithMany()
                        .HasForeignKey("LessonTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.Module", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.ModuleTopic", "ModuleTopic")
                        .WithMany()
                        .HasForeignKey("ModuleTopicId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Group");

                    b.Navigation("LessonType");

                    b.Navigation("Module");

                    b.Navigation("ModuleTopic");

                    b.Navigation("Room");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.TeacherCourseLoad", b =>
                {
                    b.HasOne("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.TeacherDraftItem", b =>
                {
                    b.HasOne("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.LessonTypeRef", "LessonType")
                        .WithMany()
                        .HasForeignKey("LessonTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.Module", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.ModuleTopic", "ModuleTopic")
                        .WithMany()
                        .HasForeignKey("ModuleTopicId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Group");

                    b.Navigation("LessonType");

                    b.Navigation("Module");

                    b.Navigation("ModuleTopic");

                    b.Navigation("Room");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.TeacherModule", b =>
                {
                    b.HasOne("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.Module", "Module")
                        .WithMany("TeacherModules")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.Teacher", "Teacher")
                        .WithMany("TeacherModules")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.TeacherWorkingHour", b =>
                {
                    b.HasOne("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.TimeSlot", b =>
                {
                    b.HasOne("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Course");
                });

            modelBuilder.Entity("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.Course", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("ModuleCourses");

                    b.Navigation("Modules");
                });

            modelBuilder.Entity("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.Module", b =>
                {
                    b.Navigation("AllowedBuildings");

                    b.Navigation("AllowedRooms");

                    b.Navigation("ModuleCourses");

                    b.Navigation("ModuleSupervisors");

                    b.Navigation("TeacherModules");

                    b.Navigation("Topics");
                });

            modelBuilder.Entity("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.Room", b =>
                {
                    b.Navigation("ModuleRooms");
                });

            modelBuilder.Entity("BlazorWasmDotNet8AspNetCoreHosted.Server.Domain.Entities.Teacher", b =>
                {
                    b.Navigation("ModuleSupervisions");

                    b.Navigation("TeacherModules");
                });
#pragma warning restore 612, 618
        }
    }
}
